baseURL = "https://bjoggis.com/"
author = "Jonas Bjørge Andersen"
title = "Bjoggis"
copyright = "Jonas Bjørge Andersen"
paginate = 10
languageCode = "en"
theme = "hugo-bearcub"

enableEmoji = true

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    # This allows Bear Cub to use a variation of Dracula that is more accessible
    # to people with poor eyesight. For more information about color contrast
    # and accessibility, see https://web.dev/color-and-contrast-accessibility/
    noClasses = false
